'use strict';
// Youdao authorization identifies the learning space; AI login is independent.
let cloudChanging=false;
let workspaceCloud={phase:'unbound',connected:false,autoSync:false};
function cloudTime(at){return at?new Date(at).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'尚未保存';}
function workspaceCloudLabel(){if(!desktop)return '云端：桌面版提供同步';return {unbound:'有道数据空间未连接',pending:workspaceCloud.error?'云端待重试 · 本机已保留':'正在等待保存到有道',syncing:'正在保存到有道',synced:'有道已保存 · '+cloudTime(workspaceCloud.lastSyncedAt),conflict:'有道与本机版本待选择',error:'有道连接失败 · 本机已保留'}[workspaceCloud.phase]||'有道数据待同步';}
function cloudCount(value){return `${value?.courses||0} 个学习会话、${value?.notes||0} 篇笔记`;}
function cloudStatusHTML(){return `<span class="cloud-dot ${workspaceCloud.phase==='synced'?'saved':''}"></span>${esc(workspaceCloudLabel())}`;}
function refreshCloudLabel(){const n=document.getElementById('workspace-cloud-state');if(n)n.innerHTML=cloudStatusHTML();const m=document.getElementById('cloud-status-detail');if(m)m.textContent=workspaceCloudLabel();}
const cloudRender=render;
render=function(where){cloudRender(where);if(cloudChanging&&busy){document.querySelectorAll('#workspace input,#workspace textarea,#workspace select,#modalroot input,#modalroot textarea,#modalroot select,#aiInput').forEach(n=>n.disabled=true);}const side=document.querySelector('.sidefoot');if(side)side.insertAdjacentHTML('beforeend',`<button class="cloud-state-link" id="workspace-cloud-state" data-action="goto('settings')">${cloudStatusHTML()}</button>`);};
const cloudSettings=settingsPage;
settingsPage=function(){const c=workspaceCloud,y=connection.youdao||{};let html=cloudSettings().replace('每台电脑独立配置密钥，学习数据可以备份与恢复。','学习数据保存在有道学习空间；这台电脑保留可离线使用的副本。').replace('<h3>有道云同步</h3>','<h3>有道账号授权</h3>').replace('确认学习记录后自动同步','确认笔记后额外生成云端 Markdown 笔记');
 const card=panel('学习数据账号与同步',`<p class="sub">使用有道账号的 API Key 授权。选择同一账号下的同一学习目录，就能在不同电脑继续学习。</p><div class="notice space"><strong id="cloud-status-detail">${esc(workspaceCloudLabel())}</strong><div class="sub space">${c.connected?'已连接：'+esc(c.folderName||y.folderName||'有道学习目录'):'授权目录：'+esc(y.folderName||'请先浏览并选择有道目录')}</div>${c.spaceId?`<div class="tiny space">学习空间 ${esc(c.spaceId)}</div>`:''}</div><p class="sub space">自动保存计划、对话、诊断、错题、课程、小闭环、作业和笔记。修改后短暂等待上传；断网时继续保存在本机，联网后可重试。</p>${c.error?`<p class="sync-error space">${esc(c.error)}</p>`:''}<div class="actions space">${btn(c.connected?'重新核对学习空间':'连接账号并恢复学习空间','connectLearningSpace()','primary')}${c.connected?btn('立即保存到有道','saveLearningCloud()')+btn('从有道获取最新数据','pullLearningCloud()'):''}${c.phase==='conflict'?btn('检查两台电脑的版本','cloudConflictModal()','danger'):''}</div><p class="tiny space">另一台电脑：安装知序 → 在有道账号授权中保存密钥 → 选择同一目录 → 连接学习空间。新电脑会恢复已有学习记录；已有本地记录时先检查版本再选择。GitHub 仅提供客户端源码、安装包与更新。</p>`);
 html=html.replace(/<section class="card"><h3>跨电脑迁移与数据<\/h3>[\s\S]*?<\/section>/,card+panel('备份与恢复',`<p class="sub">完整学习数据自动保存到上方有道学习空间。也可导出备份或保留额外云端快照，恢复前自动备份本机内容；备份不含任何账号密钥。</p><div class="actions space">${btn('导出本机备份','exportData()')}${btn('从文件恢复','importLocal()')}${btn('保存额外云端快照','uploadSnapshot()')}${btn('浏览历史快照','restoreCloud()')}${btn('打开离线数据目录','openDataFolder()')}</div>`));return html;
};
async function cloudTask(fn,replacing=false){if(busy)return toast('请等待当前任务完成');cloudChanging=replacing;window.studyDataReplacing=replacing;try{return await task(fn);}finally{cloudChanging=false;window.studyDataReplacing=false;render();}}
const beforeCloudDispatch=dispatch;
dispatch=function(code,node,event){if(cloudChanging&&busy&&code!=='closeModal()')return toast('正在恢复学习数据，请稍候');return beforeCloudDispatch(code,node,event);};
async function updateCloudResult(result){workspaceCloud=result.cloud;if(result.workspace){hydrate(result.workspace);original.save();await persist();}await refreshConnections();refreshCloudLabel();if(workspaceCloud.phase==='conflict')cloudConflictModal();}
async function connectLearningSpace(){if(busy)return toast('请等待当前任务完成');requireDesktop();if(state.page==='settings'&&!await saveConnections())return;await cloudTask(async()=>{rememberDraft();pauseActive();await persist();await updateCloudResult(await desktop.connectDataSpace());toast(workspaceCloud.phase==='conflict'?'已有数据需要检查版本':'有道学习空间已连接，完整数据已回读核对');},true);}
async function saveLearningCloud(){await task(async()=>{requireDesktop();rememberDraft();await persist();await updateCloudResult(await desktop.syncWorkspace());toast(workspaceCloud.phase==='synced'?'完整学习数据已保存到有道并回读核对':'数据保存在本机，请检查云端状态');});}
async function pullLearningCloud(){await cloudTask(async()=>{requireDesktop();rememberDraft();pauseActive();await persist();await updateCloudResult(await desktop.pullWorkspace());toast(workspaceCloud.phase==='conflict'?'恢复前请检查两份版本':'已获取有道最新学习数据');},true);}
function cloudConflictModal(){const c=workspaceCloud.conflict;if(!c)return toast('目前没有待选择的版本');openModal('检查学习数据版本',`<p>${esc(c.reason)}</p><div class="grid2 space"><div class="notice"><strong>这台电脑</strong><p>${cloudCount(c.local?.counts)}</p><p class="sub">${cloudTime(c.local?.at)}</p></div><div class="notice"><strong>有道学习空间</strong><p>${cloudCount(c.remote?.counts)}</p><p class="sub">${cloudTime(c.remote?.at)}</p></div></div>${c.preview?.changedNotes?.length?`<p class="space">笔记内容变化：${esc(c.preview.changedNotes.join('、'))}</p>`:''}<p class="sub space">计划、对话、课程与作业作为完整版本一起恢复，当前版本会保留备份。选择本机版本时，有道原版本也会备份。</p><div class="actions space">${c.remoteHash?btn('采用有道版本到本机',"resolveLearningCloud('remote')",'primary'):''}${btn('采用本机版本到有道',"resolveLearningCloud('local')")}${btn('稍后处理','closeModal()')}</div>`);}
async function resolveLearningCloud(choice){await cloudTask(async()=>{requireDesktop();rememberDraft();pauseActive();await persist();await updateCloudResult(await desktop.resolveWorkspaceConflict(choice));if(workspaceCloud.phase!=='conflict'){closeModal();toast('版本已保存并核对，原数据已保留备份');}},true);}
const beforeCloudRefresh=refreshConnections;
refreshConnections=async function(){await beforeCloudRefresh();workspaceCloud=await desktop.cloudStatus();refreshCloudLabel();};
const beforeCloudFolder=chooseSyncFolder;
chooseSyncFolder=async function(id,name){await beforeCloudFolder(id,name);workspaceCloud=await desktop.cloudStatus();render();toast('目录已选择，请连接学习空间以恢复或保存完整数据');};
['connectLearningSpace','saveLearningCloud','pullLearningCloud','cloudConflictModal','resolveLearningCloud'].forEach(n=>actions.add(n));
if(desktop){desktop.onEvent(event=>{if(event.type==='workspace-cloud'){workspaceCloud=event.cloud;refreshCloudLabel();if(state.page==='settings'&&!busy&&!document.activeElement?.matches('input,textarea,select'))render();}});desktop.cloudStatus().then(value=>{workspaceCloud=value;refreshCloudLabel();}).catch(showError);}else render();
