// Account model catalogues and separately stored AI connections.
let editProfileId='';
function allProfiles(){return connection.aiProfiles?.length?connection.aiProfiles:[{id:'codex',name:'Codex 账号',provider:'codex',models:[]},{id:'deepseek',name:'DeepSeek',provider:'api',baseUrl:'https://api.deepseek.com',model:'',models:[]}];}
function editingProfile(){return allProfiles().find(p=>p.id===editProfileId)||allProfiles().find(p=>p.id===connection.activeAI)||allProfiles()[0];}
aiLabel=function(){const p=allProfiles().find(p=>p.id===connection.activeAI);return p?(p.name+' · '+(p.model||'请选择模型')):isCodex()?'Codex 账号':'AI 未配置';};
aiConfigured=function(){return !!desktop&&(isCodex()?codexState.loggedIn:!!connection.ai.baseUrl&&!!connection.ai.model&&(connection.hasAiKey||/^https?:\/\/(localhost|127\.0\.0\.1)(:|\/|$)/.test(connection.ai.baseUrl)));};
const providerRender=render;
render=function(where){providerRender(where);const controls=document.querySelector('.topcontrols');if(controls){controls.insertAdjacentHTML('afterbegin',`<select class="input quick-ai" aria-label="切换 AI" data-change="selectAIProfile(this.value)" ${busy?'disabled':''}>${allProfiles().map(p=>`<option value="${esc(p.id)}" ${p.id===(connection.activeAI||'codex')?'selected':''}>${esc(p.name)}</option>`).join('')}</select>`);}};
const providerSettings=settingsPage;
settingsPage=function(){const p=editingProfile(),list=p.models||[];const missing=p.model&&!list.some(m=>m.id===p.model);const html=providerSettings();const card=panel('AI 服务',`<p class="sub">各服务的密钥和模型独立保存。顶部可随时切换当前使用的 AI。</p><div class="field"><label>管理服务</label><select id="profile-id" class="input" data-change="editAIProfile(this.value)">${allProfiles().map(x=>`<option value="${esc(x.id)}" ${x.id===p.id?'selected':''}>${esc(x.name)}${x.id===connection.activeAI?'（正在使用）':''}</option>`).join('')}</select></div><div class="field"><label>服务名称</label><input id="profile-name" class="input" maxlength="40" value="${esc(p.name)}"></div>${p.provider==='codex'?`<div class="notice space">${esc(codexState.message)}</div><p class="sub space">使用本机 Codex / ChatGPT 登录与额度。另一台电脑首次使用时登录自己的账号。</p>`:`<div class="field"><label>接口基础地址</label><input id="profile-url" class="input" value="${esc(p.baseUrl||'')}" placeholder="https://服务地址/v1"></div><div class="field"><label>API Key（${p.hasKey?'已加密保存，留空保留':'尚未配置'}）</label><input id="profile-key" type="password" class="input" autocomplete="off"></div><label class="sub"><input id="profile-json" type="checkbox" ${p.jsonMode!==false?'checked':''}> 服务支持 JSON 模式</label>`}<div class="field"><label>模型</label><select id="profile-model" class="input" ${!list.length&&!missing?'disabled':''}>${!list.length&&!missing?'<option value="">获取模型后选择</option>':''}${missing?`<option value="${esc(p.model)}" selected>${esc(p.model)}（需刷新确认）</option>`:''}${list.map(m=>`<option value="${esc(m.id)}" ${p.model===m.id?'selected':''}>${esc(m.label||m.id)}${m.label&&m.label!==m.id?' · '+esc(m.id):''}</option>`).join('')}</select><p class="tiny">${p.modelsAt?'列表更新于 '+new Date(p.modelsAt).toLocaleString():'从当前账号或服务获取可用模型。'}</p></div><div class="actions space">${btn('保存并获取模型',"saveAIProfileForm('models')",'primary')}${btn('保存设置',"saveAIProfileForm('save')")}${p.id!==connection.activeAI?btn('使用这个服务',`selectAIProfile('${p.id}')`):badge('正在使用','green')}${p.provider==='codex'?btn('登录 ChatGPT 账号','loginCodex()'):btn('清除该服务密钥',`clearProfileKey('${p.id}')`,'small')}${btn('添加其他 AI','newAIProfileModal()','small')}</div>`);return html.replace(/<section class="card"><h3>AI 服务<\/h3>[\s\S]*?<\/section>/,card).replace('目标目录 ID（可留空；可从云端目录浏览复制）','目标目录'+(connection.youdao.folderName?' · '+esc(connection.youdao.folderName):'（浏览目录后选择）'));};
function editAIProfile(id){if(busy)return;editProfileId=id;render();}
async function saveAIProfileForm(mode){const p=editingProfile(),input={id:p.id,name:document.getElementById('profile-name').value,provider:p.provider,model:document.getElementById('profile-model').value,baseUrl:document.getElementById('profile-url')?.value||'',jsonMode:document.getElementById('profile-json')?.checked!==false};const key=document.getElementById('profile-key')?.value;if(key)input.apiKey=key;await task(async()=>{requireDesktop();connection=await desktop.saveAIProfile(input);const keyField=document.getElementById('profile-key');if(keyField)keyField.value='';if(mode==='models'){connection=await desktop.fetchAIModels(p.id);toast('模型列表已获取，请选择模型后保存');}else toast('该服务设置已保存');});render();}
async function selectAIProfile(id){if(busy)return;await task(async()=>{requireDesktop();const result=await desktop.selectAIProfile(id);connection=result.config;codexState=result.codex;toast('已切换到 '+connection.ai.name);});render();}
useCodexAccount=async function(){await selectAIProfile('codex');};
function newAIProfileModal(){openModal('添加 AI 服务',`<p class="sub">支持提供模型列表的 OpenAI 兼容服务，也可连接本地模型。</p><div class="field"><label>服务名称</label><input id="new-profile-name" class="input" placeholder="例如：本地模型" maxlength="40"></div>${btn('添加配置','createAIProfile()','primary space')}`);}
async function createAIProfile(){const name=document.getElementById('new-profile-name').value.trim();if(!name)return toast('请填写服务名称');await task(async()=>{requireDesktop();const result=await desktop.createAIProfile(name);connection=result.config;editProfileId=result.id;closeModal();});render();}
function clearProfileKey(id){openModal('清除该服务密钥',`<p>清除后需要重新填写，其他服务仍可使用。</p>${btn('确认清除',`confirmClearProfileKey('${id}')`,'danger space')}`);}
async function confirmClearProfileKey(id){await task(async()=>{requireDesktop();connection=await desktop.clearAIProfileKey(id);closeModal();});render();}
saveConnections=async function(){try{requireDesktop();const config={youdao:{...connection.youdao,folderId:document.getElementById('youdao-folder').value.trim(),autoSync:document.getElementById('auto-sync').checked},updates:{owner:document.getElementById('update-owner').value.trim(),repo:document.getElementById('update-repo').value.trim()},reminders:{enabled:document.getElementById('reminder-enable').checked,time:document.getElementById('reminder-time').value,startup:document.getElementById('reminder-startup').checked}};const key=document.getElementById('youdao-key').value;if(key)config.youdaoKey=key;connection=await desktop.saveConfig(config);render();toast('同步、提醒与更新设置已保存');return true;}catch(e){showError(e);return false;}};
browseCloud=async function(folder){await task(async()=>{requireDesktop();const list=await desktop.listCloud(folder);openModal('选择有道同步目录',`<div class="actions">${folder?btn('回到根目录','browseCloud()','small'):''}</div>${list.map(x=>`<div class="item"><div class="grow"><strong>${esc(x.title)}</strong></div>${x.directory?btn('设为同步目录',`chooseSyncFolder('${x.id}','${encodeURIComponent(x.title).replace(/'/g,'%27')}')`,'small')+btn('进入',`browseCloud('${x.id}')`,'small'):btn('读取',`readCloudNote('${x.id}')`,'small')}</div>`).join('')||'<p>目录为空。</p>'}`);});};
async function chooseSyncFolder(id,name){await task(async()=>{connection=await desktop.selectSyncFolder({id,name:decodeURIComponent(name)});closeModal();toast('同步目录已设为 '+connection.youdao.folderName);});render();}
['saveAIProfileForm','selectAIProfile','editAIProfile','newAIProfileModal','createAIProfile','clearProfileKey','confirmClearProfileKey','chooseSyncFolder'].forEach(name=>actions.add(name));
document.addEventListener('change',event=>{const match=event.target.dataset.change?.match(/^(selectAIProfile|editAIProfile)\(this.value\)$/);if(match){const result=window[match[1]](event.target.value);if(result?.catch)result.catch(showError);}});
if(!desktop)render();

