'use strict';

// Self-authored task packs. A wrong option is a hypothesis for follow-up,
// never a diagnosis of a whole module or a prediction of an exam score.
const examTracks=(()=>{
  const source='知序自编任务材料 · 非考试真题；不预测官方分数';
  const choice=(id,material,prompt,options,expected,reason,moduleIds)=>{
    const errorLinks={};options.forEach((option,i)=>{const letter=String.fromCharCode(65+i);if(letter!==expected)errorLinks[letter]={reason:'选择“'+option+'”与当前任务依据不符：'+reason+' 可能遗漏条件、范围或推理步骤，需换一份新材料复查；这不是整个模块的能力结论。',moduleIds};});
    return {id,material,prompt:material?material+'\n\n'+prompt:prompt,options:options.map((x,i)=>String.fromCharCode(65+i)+'. '+x),answer:expected,expected,reason,format:'点击选项作答，可补充材料中的依据。',grading:'exact',moduleIds,scope:prompt,errorLinks,optionFaults:errorLinks};
  };
  const diagnostic=(id,material,prompt,options,expected,reference,moduleId,relatedModuleIds,scope,faults)=>{
    const moduleIds=[moduleId,...relatedModuleIds],errorLinks={};
    options.forEach((_,i)=>{const letter=String.fromCharCode(65+i);if(letter!==expected)errorLinks[letter]={reason:'可能的错因：'+faults[letter]+'。需用另一份新材料复查，单题不能确定整个模块的能力。',moduleIds};});
    return {id,prompt,material,options,expected,reference,criteria:[scope,'能够指向材料中的对应证据，区分已知信息与推断'],grading:'choice',moduleId,relatedModuleIds,moduleIds,scope,errorLinks,optionFaults:errorLinks};
  };
  const activity=(id,form,title,instructions,content,moduleIds)=>({id,form,title,instructions,content,moduleIds});
  const pack=t=>({...t,source,priority:'P1',minutes:t.minutes||35,hwMinutes:t.hwMinutes||10,prereq:'从完整任务的当前表现开始；错题关联只作为待复查线索，已有基础可直接尝试独立新题。',goal:t.practicalOutput,example:t.scenario,targetForms:t.activities.map(a=>a.form),relations:t.relations||t.modules.slice(1).map(id=>({from:t.modules[0],to:id,reason:'在同一主题任务中连接材料证据、解释规则与迁移产出。'})),testModuleIds:t.tests.map(group=>group.map((q,i)=>q.moduleIds||t.criterionModuleIds[i])),homeworkModuleIds:t.homework.map(()=>t.modules)});

  const campusMaterial=`Northbridge College is deciding how to improve its library. A student survey found that silent seats were full after 6 p.m., but group rooms were often empty because bookings closed at 5 p.m. The college first considered keeping the entire building open until midnight. This would require two extra security staff every evening.

The library team instead proposed a six-week trial. Only the ground floor would stay open until 10 p.m.; students could book its group rooms online until 9 p.m. The upper floor, which contains rare books, would still close at 6 p.m. Although the trial adds fewer silent seats than the midnight plan, it can run within the current security budget.

Students will be asked how long they wait for a seat and whether a booked room is available when they arrive. The team will compare these results with the month before the trial. If waiting times fall without a rise in security incidents, the college will consider extending the trial. No decision about permanent opening hours has yet been made.`;
  const enDiagnosticMaterial=`Riverside University used to issue paper travel passes to students who lived more than three kilometres from campus. In September, it introduced a digital pass for all full-time students, including those living nearby. The aim was to reduce short car journeys, rather than to lower the university's transport spending.

During the first eight weeks, bus use increased by 18 percent compared with the same period a year earlier. The university's report warns that this change cannot be attributed entirely to the pass: a new bus route opened at the same time. Students who answered an online survey said the pass was convenient, although many wanted buses to run later in the evening. Part-time students were not included in this survey.

The university will review the scheme after a full academic year. It has not yet decided whether to extend the pass to part-time students. Until that review, existing paper passes will remain valid for students who already hold them.`;
  const enDiagnostic=[
    diagnostic('en-diag-purpose',enDiagnosticMaterial,'What was the main aim of the digital-pass scheme?',['To reduce short car journeys','To cut university transport spending','To serve only students living far away','To replace the new bus route'],'A','材料第一段明确说 reduce short car journeys，并用 rather than 排除降低支出。','en-reading',['en-relations'],'找出目的并正确理解 rather than 的排除关系',{B:'把 rather than 后被排除的目标当作实际目的',C:'把旧政策的居住条件搬到新政策',D:'把同时发生的公交线路变化当作政策目标'}),
    diagnostic('en-diag-cause',enDiagnosticMaterial,'Which conclusion is supported by the report?',['The pass alone caused the whole increase','The new route had no effect on bus use','More than one change may have affected bus use','Bus use increased only among part-time students'],'C','第二段 cannot be attributed entirely to the pass 限制因果归因，新线路也是同时发生的变化；材料没有量化各自贡献。','en-reading',['en-structure','en-relations'],'识别否定范围与谨慎因果结论',{A:'遗漏 cannot 与 entirely 对因果结论的限制',B:'将未量化的因素当作已排除的因素',D:'混淆公交使用数据和排除非全日制学生的问卷样本'}),
    diagnostic('en-diag-survey',enDiagnosticMaterial,'Which group was NOT included in the online survey?',['Students living nearby','Full-time students with digital passes','Students using the new bus route','Part-time students'],'D','原文 Part-time students were not included in this survey.；此结论仅限定问卷样本，不等于他们从未乘公交。','en-reading',['en-structure'],'准确处理被动否定句及其适用范围',{A:'将旧距离门槛误用于问卷对象',B:'将政策受益者误判为被排除的样本',C:'把未说明的乘车路线当作排除条件'}),
    diagnostic('en-diag-future',enDiagnosticMaterial,'What has the university decided about part-time students?',['They will receive digital passes next month','No extension decision has yet been made; a review is planned','Their paper passes are already invalid','They will never be eligible for any pass'],'B','末段 has not yet decided 与 will review 表明尚未决定且审查在计划中；until...remain valid 描述等待审查时旧通行证的状态。材料没有承诺审查后必定立即作出决定。','en-reading',['en-tense','en-writing'],'区分过去执行、当前未决定和未来审查',{A:'把审查计划读成确定的发放承诺',C:'忽略 remain valid 的持续状态',D:'把 not yet 的暂未决定扩大成永久否定'})
  ];

  const enCampus=pack({
    key:'en-campus-library',subject:'en',title:'校园图书馆改造：从阅读证据到方案建议',theme:'校园服务与资源安排',examTaskType:'雅思阅读风格的信息定位与结论范围 + 证据支持的短写作',practicalOutput:'读懂图书馆试点方案，区分原因、让步与未决定事项，写出带证据且保留条件的服务建议。',modules:['en-reading','en-relations','en-structure'],scenario:campusMaterial,
    teaching:'先把自己放在决策者的位置：方案解决什么问题、代价是什么、何时才能扩展？把句子拆成“主体—动作—条件/限制”，再定位证据。Although A, B 允许 A 为真，但 B 是主要论断；which 引导的补充说明帮助识别对象，不能改变主句承诺。阅读选择题要求选材料支持的结论，不能把 consider extending 写成 already made permanent。错题后只补当前任务中影响理解的让步、指代或否定范围，再回到一份新材料验证。',
    activities:[
      activity('campus-map','reading','画出试点决策卡','从材料摘出：现有问题、被放弃方案的成本、试点范围、扩展条件；每项写一句证据。',campusMaterial,['en-reading','en-structure']),
      activity('campus-contrast','comparison','核对两种概括','判断下面两句哪一句保留了原文限制，并解释另一句扩大了什么。','概括一：The college will permanently keep all floors open until midnight.\n概括二：The college is testing limited late opening before deciding whether to extend it.\n再拆解：Although the trial adds fewer silent seats than the midnight plan, it can run within the current security budget.',['en-reading','en-relations','en-structure']),
      activity('campus-memo','explanation','给学生会写建议','用三句中文或英语向学生会说明：为什么先试点、需要收集什么证据、现阶段不能保证什么。然后重写其中一句，让 although 或 if 的关系明确。','建议必须同时引用费用限制和试点评估指标；不要自行编造调查结果或永久开放决定。',['en-reading','en-relations'])
    ],
    diagnosis:choice('campus-entry',campusMaterial,'Which question does the trial mainly help the college answer?',['Can a limited extension improve access within current resources?','Can rare books be moved outdoors?','Can every floor be opened without staff?','Can surveys replace all security measures?'],'A','试点连接座位可及性、现有预算和安全观察。',['en-reading','en-structure']),
    practice:choice('campus-practice',campusMaterial,'What does the sentence beginning “Although” tell us?',['The trial adds more seats and costs more','The trial gives fewer additional silent seats but fits the budget','The midnight plan has already begun','The security budget has been cancelled'],'B','让步从句承认增加座位较少，主句强调预算可行。',['en-reading','en-relations','en-structure']),
    criteria:['从新材料定位方案限制与证据，避免扩大结论','拆解让步、条件或修饰结构，解释其如何改变任务结论'],
    criterionModuleIds:[['en-reading','en-structure'],['en-reading','en-relations','en-structure']],
    tests:[[
      choice('campus-test-a1','Westlake College trialled online lab bookings for one month. Bookings could be made until 7 p.m., but laboratory access still ended at 8 p.m. The report measured missed bookings; it did not measure experiment quality.','Which claim is supported?',['The trial proved experiments became more accurate','Students could enter the lab after 8 p.m.','The report considered booking reliability rather than experiment quality','All missed bookings disappeared'],'C','材料限定测量对象为 missed bookings，未测实验质量。',['en-reading','en-structure']),
      choice('campus-test-a2','Although a shuttle serves fewer stops than the old bus, it reaches the examination hall ten minutes earlier. The college will add stops only if a second vehicle is funded.','Which summary preserves both relations?',['The shuttle is faster, and extra stops depend on new funding','The shuttle already serves every old stop','Adding stops will make a second vehicle unnecessary','Fewer stops mean the shuttle always arrives later'],'A','although 对比服务范围与到达时间；only if 限定增设站点的必要条件。',['en-reading','en-relations','en-structure'])
    ],[
      choice('campus-test-b1','Easton University tested self-service printing in two residence halls. Students in other halls continued using staffed print rooms. The university plans to compare waiting times before deciding whether to expand the service.','What can be concluded now?',['Self-service printing has been adopted in every hall','Waiting-time comparisons will inform a later expansion decision','Staffed print rooms are permanently closed','Printing costs have certainly fallen'],'B','试点范围仅两栋，扩展仍待比较结果；没有成本结论。',['en-reading','en-structure']),
      choice('campus-test-b2','The meeting room, which was previously reserved for staff, is now available to student societies. However, societies must book it at least two days in advance.','Which interpretation is accurate?',['The room remains staff-only','The relative clause cancels the booking rule','Students can use the room without any notice','Access has expanded, but an advance-booking condition remains'],'D','which 描述原先用途，however 引出当前限制；主句开放不取消预约条件。',['en-reading','en-relations','en-structure'])
    ]],
    hwCriteria:['以新任务材料中的具体证据比较两个选择，保留范围与限制','提交可执行的建议段落，至少清楚表达一个转折/让步和一个条件关系'],homeworkCriterionModuleIds:[['en-reading','en-structure'],['en-reading','en-relations','en-structure']],
    homework:[
      {prompt:'新任务：学院有两种周末辅导方案。方案A：周六9:00–12:00由两名教师现场答疑，最多30人；学生必须周五前预约。方案B：周日20:00–21:00在线答疑，最多80人；目前网络稳定性未经评估，教师不能承诺逐个回答。预算只能支持一种方案试行四周。\n提交① 用材料证据比较可及性和限制（至少两项）；② 给院系一段60–90词英文建议，说明你选哪种、为什么以及什么条件下调整。可选任一方案，但不得把未知网络稳定性写成已证实。',answers:['比较明确指出A现场名额30且有预约/时间限制，B名额80和夜间线上可及性但网络稳定性未评估且不能逐个回答；不编造试点效果。','建议选择任一方案并以题干限制支持；英文段落包含准确的转折或让步及条件，如although/but与if；提出四周后依据反馈或可核查指标调整，不声称未知结果。'],grading:'semantic',executionRequired:false},
      {prompt:'替代新任务：学生中心准备试行延长咖啡厅营业。方案A每晚延长到21:00，但仅提供冷餐；方案B只在周二周四延长到22:00，可提供热餐但多需一名员工。调查只问了住校生，未问通勤生。\n提交① 两个方案的证据比较与调查范围限制；② 60–90词英文建议，给出条件性实施方案和一个后续观察指标。不要把住校生反馈当作全体学生结论。',answers:['比较准确包含A每晚/21点/冷餐，B两晚/22点/热餐/额外员工至少两个真实差异；明确问卷只覆盖住校生，不支持通勤生或全体偏好。','建议理由与材料一致，有准确转折或让步及条件关系，说明何时采用或调整并提出可观察指标如两类学生使用情况/等待时间/成本；不伪造既有统计结果。'],grading:'semantic',executionRequired:false}
    ],
    review:choice('campus-review','A university opened one study lounge overnight during exams. Although attendance was high on weekdays, weekend use remained low. The university will repeat the trial in winter before making a permanent decision.','Which is the safest summary?',['Permanent overnight opening is confirmed','Weekend and weekday use were equally high','Weekday demand was promising, but another trial precedes a permanent decision','Winter trials have already finished'],'C','保留让步与未来试验顺序，避免把试点扩大为永久决定。',['en-reading','en-relations','en-structure'])
  });

  const cityMaterial=`A coastal town launched a bike-share trial in April. Its first twenty stations were placed near railway stops and large workplaces. At first, bikes could be returned only to the station from which they had been hired. In June, the operator allowed returns at any station with an empty space.

The change made one-way trips possible, yet it created an uneven distribution of bikes. On weekday mornings, stations near the seafront ran out of bikes while those near the railway filled up. The operator began moving bikes before the morning rush and publishing live station information. These measures reduced complaints about unavailable bikes, but the report did not claim that every station was balanced throughout the day.

A proposal to add stations near schools has been delayed. The town wants to consult families about safe routes before choosing sites. It is also considering discounted memberships, though no price or starting date has been announced.`;
  const enCity=pack({key:'en-city-bikes',subject:'en',title:'城市共享单车：追踪变化与解释证据',theme:'城市出行与服务改进',examTaskType:'雅思阅读风格的时间线、指代与信息边界 + 改写',practicalOutput:'在城市出行材料中整理改革前后的规则，解释措施与结果的联系，并向居民给出准确的出行建议。',modules:['en-reading','en-tense','en-writing'],scenario:cityMaterial,
    teaching:'先标出 April、at first、in June、began、has been delayed、is considering 等时间信号，再把“已发生的变化”“目前状态”“尚未决定的计划”分开。These measures 指向紧邻的调度与信息发布，不是所有未来提案。改写时保留数量、条件与确定程度：reduced complaints 不能写成 solved all shortages；is considering 不等于 will definitely。只在错题需要时回看时态或指代，随后用另一个城市服务材料验证。',
    activities:[activity('city-timeline','reading','为通勤者画时间线','列出最初规则、六月变化、随后措施和两个未落地的提案。每个节点保留时间或状态词。',cityMaterial,['en-reading','en-tense']),activity('city-rewrite','translation','把公告改写为准确短句','把中文公告改写成三句英文：六月起可以异站还车；运营方已经开始早高峰前调车；学校站点和会员折扣尚未确定。核对你的动词是否改变确定程度。','可参照材料原意，但不用逐词翻译；不承诺价格、日期或所有站点始终有车。',['en-reading','en-tense','en-writing']),activity('city-edit','debugging','纠正夸大宣传','找出宣传稿至少两处与材料不符，给出带依据的修订。','宣传稿：Since April, riders have always returned bikes to any station. The operator has eliminated every shortage. Discounted memberships will begin next week.',['en-reading','en-tense','en-writing'])],
    diagnosis:choice('city-entry',cityMaterial,'Which change first made one-way journeys possible?',['Publishing a discount price','Returning bikes to a different station with space','Choosing school routes','Closing railway stations'],'B','六月改动取消必须原站归还的限制。',['en-reading','en-tense']),
    practice:choice('city-practice',cityMaterial,'Which rewritten announcement is accurate?',['Discounts started in April','All stations stay balanced all day','The town is still considering discounts','School stations are already open'],'C','is considering 加未公布价格日期，说明仍在考虑。',['en-reading','en-tense','en-writing']),criteria:['从新城市服务材料重建事件顺序与当前状态','准确改写材料结论，保留时态、数量和未定限制'],criterionModuleIds:[['en-reading','en-tense'],['en-reading','en-tense','en-writing']],
    tests:[[
      choice('city-test-a1','A town tested demand-responsive buses in January. Initially, bookings closed a day before travel. Since March, residents have been able to book until two hours before departure. A weekend extension is still under discussion.','Which rule is currently in effect?',['All weekend trips are available','Bookings close one day before every trip','Bookings may be made up to two hours before departure','Bookings are no longer required'],'C','Since March 对应当前两小时前预约规则；周末扩展未定。',['en-reading','en-tense']),
      choice('city-test-a2','New signs have reduced complaints about finding the ferry terminal. The council has not measured whether journey times have changed.','Which rewrite preserves the evidence?',['The signs made every journey faster','Complaints fell, but journey-time effects have not been measured','The council proved the signs have no effect','Nobody has complained since the signs appeared'],'B','减少投诉不等于没人投诉，未测耗时不等于耗时变化或无效。',['en-reading','en-tense','en-writing'])
    ],[
      choice('city-test-b1','A tram operator introduced mobile tickets in February. In May it added ticket machines at six stations. Staff will survey passengers in November before deciding on further machines.','What has already happened?',['A passenger survey in November','Installation of machines at six stations','A decision to add machines at every station','Withdrawal of all mobile tickets'],'B','五月安装已完成，十一月问卷和进一步决定仍在未来。',['en-reading','en-tense']),
      choice('city-test-b2','The new parking system is being tested in the north district. Early data suggest fewer payment errors, but the trial includes only council-owned car parks.','Which public statement is justified?',['The system has solved all parking problems across the city','Every private car park is included','Payment errors may have fallen in the tested council-owned car parks','The trial has proved private car parks perform worse'],'C','suggest 谨慎判断且范围限北区公营停车场，不能推广全市或私营。',['en-reading','en-tense','en-writing'])
    ]],
    hwCriteria:['正确整理新材料中已完成、持续状态与尚未决定的事项','用英文改写发布准确的服务提示，保留范围与确定程度'],homeworkCriterionModuleIds:[['en-reading','en-tense'],['en-reading','en-tense','en-writing']],homework:[
      {prompt:'新材料：Harbour Town tested real-time ferry displays at two terminals in May. Since August, displays have shown cancelled sailings as well as delays. Passengers in a small survey reported fewer missed announcements. The council has not surveyed passengers at the three terminals without displays, and it is considering an expansion for next spring.\n提交① 用三行整理已发生变化、当前规则和未定计划，指出调查限制；② 写60–90词英文乘客提示，包含当前用途和不能承诺的事项。',answers:['准确区分五月两站试点、八月起展示延迟和取消、明年春季扩展仍在考虑；样本小且不含另外三站，不能推全镇效果。','英文提示保留two terminals、since August与considering的确定程度；说明显示延迟/取消并避免保证不会误船或所有站已覆盖；以清楚时态表达现在用途与未来未定。'],grading:'semantic',executionRequired:false},
      {prompt:'替代材料：Metroville offered off-peak rail discounts in June on weekdays only. In September the booking app began showing the discount before payment. A survey of 120 app users found fewer price complaints. Paper-ticket customers were not surveyed. Weekend discounts remain under review.\n提交① 事件/当前状态/待决定事项表，并说明样本限制；② 60–90词英文出行说明，不将投诉减少改写为普遍降价或周末优惠已实施。',answers:['准确列六月工作日非高峰优惠、九月付款前显示折扣、周末仍审查；120名app用户不代表纸票乘客及所有旅客。','英文说明保留工作日非高峰条件和现有app展示功能，使用正确过去/当前/未定时态；不声称全时段降价、零投诉或周末优惠已定。'],grading:'semantic',executionRequired:false}
    ],review:choice('city-review','In February a city installed water-refill points in four parks. It has recorded water use there since April. More sites are being considered, but no locations have been selected.','Which summary is accurate?',['Sites beyond the four parks are already selected','Water-use recording began before installation','The city records use at existing sites while considering expansion','Every park now has a refill point'],'C','已安装/持续记录/考虑未来扩展是不同状态。',['en-reading','en-tense','en-writing'])});

  const techMaterial=`A research team tested an automatic system for identifying damaged fruit from photographs. The training collection contained pictures taken in a studio, where the background and lighting were controlled. On a separate studio test set, the system correctly classified most images.

When the team tested it on a conveyor belt in a packing centre, accuracy fell. Fruit partly hidden behind other fruit was especially difficult to identify. Changing the camera position improved the results, suggesting that the image conditions contributed to the problem. However, the team did not conclude that camera position was the only cause.

The system is intended to flag uncertain cases for a worker to inspect, not to remove human inspection entirely. The researchers plan to test it during the winter harvest, when different varieties arrive. Until then, the results apply only to the varieties and conditions already studied. The report also notes that purchasing faster hardware would not by itself supply the missing examples.`;
  const enTech=pack({key:'en-tech-inspection',subject:'en',title:'科技检测方案：判断结论是否有足够证据',theme:'科技应用与研究证据',examTaskType:'雅思阅读风格的主旨、推断与论证边界 + 建议表达',practicalOutput:'读懂技术试验的用途、限制与改进依据，区分观察和因果猜测，并提出有条件的后续验证建议。',modules:['en-reading','en-structure','en-writing'],scenario:techMaterial,
    teaching:'技术材料要分开“测试条件、观察、解释、用途、下一步”。which/where 从句可能限定样本或环境；the only cause 与 contributed to 不是同等强度；not...entirely 和 not by itself 限制替代或充分性。先给每个结论找支撑句，再看支撑的范围是否一致。错在结构解析时才补主句与修饰范围，错在结论夸大时补证据表达；随后换材料检验能否仍保留条件。',activities:[activity('tech-evidence','reading','建立证据分层表','写出“在什么环境观察到什么、作者提出什么解释、什么仍未知”三个栏。每栏引用材料细节。',techMaterial,['en-reading','en-structure']),activity('tech-claims','comparison','检查三条采购主张','按材料标注支持/不支持/仍未知，并指出理由。','主张① 更快硬件本身就能补齐数据样本。\n主张② 相机调整可能缓解一部分现场问题。\n主张③ 试验已经证明所有冬季品种都适用。',['en-reading','en-structure']),activity('tech-proposal','explanation','写给包装中心经理','用60–80词英文说明这个系统现在适合承担什么角色、为什么仍需人工，以及冬季试验应先检查哪种边界。','提案需保留“标出不确定样本给工人检查”的用途；不能把计划中的验证写成已完成。',['en-reading','en-writing','en-structure'])],
    diagnosis:choice('tech-entry',techMaterial,'What is the system intended to do?',['Replace every worker immediately','Flag uncertain cases for human inspection','Guarantee all winter varieties are identified','Make studio photographs unnecessary'],'B','材料给出辅助筛选用途，并明确不完全替代人工。',['en-reading','en-structure']),practice:choice('tech-practice',techMaterial,'What follows from the camera-position change?',['Camera position may be one contributing factor','Hardware speed is the only cause','The team proved lighting never matters','No further testing is useful'],'A','improved/suggesting/contributed 支持部分因素而非唯一因果。',['en-reading','en-structure']),criteria:['区分新科技材料中的观察、解释、用途与未验证范围','选择或写出保留证据强度与样本限制的表达'],criterionModuleIds:[['en-reading','en-structure'],['en-reading','en-structure','en-writing']],
    tests:[[
      choice('tech-test-a1','A speech tool was tested with recordings from adults in quiet offices. It performed well there. Results for children or crowded railway stations have not been collected.','Which evaluation is justified?',['The tool is proven for children in crowds','The study demonstrates results within a limited adult, quiet-office setting','Crowded stations will certainly improve accuracy','No adult can use the tool'],'B','样本与场景限制只支持已有条件结果。',['en-reading','en-structure']),
      choice('tech-test-a2','A farm found that a new moisture sensor reduced unnecessary watering in one greenhouse. Temperature settings changed during the trial as well, so the report does not isolate the sensor’s contribution.','Which report sentence preserves the findings?',['The sensor alone caused the entire improvement','Temperature can never affect watering','The trial guarantees the same result on every farm','Unnecessary watering fell, but the sensor’s separate effect remains uncertain'],'D','观察下降真实，因同时变温度不能独立归因，也不能外推所有农场。',['en-reading','en-structure','en-writing'])
    ],[
      choice('tech-test-b1','Engineers tested a delivery robot on dry indoor floors. It stopped correctly at marked crossings. Tests on wet surfaces are planned but have not begun.','Which distinction is correct?',['Wet-surface performance is an observed result','Dry-floor results are evidence; wet-surface performance is still untested','Marked crossings were never tested','All outdoor weather has been covered'],'B','区分已测试条件与未来计划。',['en-reading','en-structure']),
      choice('tech-test-b2','A translation system helps volunteers draft messages. Volunteers must check names and dates before sending them. The system is not intended to provide legal advice.','Which user guidance is accurate?',['Send drafts automatically because checking is optional','Use it for legal decisions instead of a professional','Use it to draft messages, verify key details, and respect the stated scope','Every drafted name and date has already been verified'],'C','改写必须保留辅助草稿、核查要求与用途限制。',['en-reading','en-structure','en-writing'])
    ]],hwCriteria:['明确列出新任务的证据条件、可支持结论及未知范围','提交准确英文方案，包含人工/后续验证要求而不将假设写成事实'],homeworkCriterionModuleIds:[['en-reading','en-structure'],['en-reading','en-structure','en-writing']],homework:[
      {prompt:'新材料：A clinic tested a reminder app with 50 adult volunteers who owned smartphones. Missed appointments were lower during the four-week trial than in the previous month. Receptionists also began making extra phone calls during the trial. Patients without smartphones were not included. The app does not give medical advice.\n提交① 证据表：对象/时间、观察、不能独立确定的因果、未覆盖人群；② 写70–100词英文给诊所经理建议，说明可试行用途、仍需什么验证与为什么不能直接扩大结论。',answers:['准确列50成人智能手机用户/四周、爽约减少但同时加电话不能归因为app单独作用、无智能手机患者未覆盖；不声称医学效果。','英文提案将app用于提醒且保留无医疗建议用途限制，提出区分电话与app效果或覆盖不同人群的后续验证；条件性措辞与材料一致，无普遍效果保证。'],grading:'semantic',executionRequired:false},
      {prompt:'替代材料：A museum tested automatic audio-guide recommendations with 40 visitors who selected English. Visitors listened to more exhibits than in the previous trial. The exhibition route was shortened at the same time. Other guide languages and wheelchair-accessible routes were not evaluated. Staff will review these cases later.\n提交① 证据/可能混杂因素/未覆盖范围表；② 写70–100词英文建议，向馆方说明目前可以说什么、下一轮测试什么。不得承诺提供材料中不存在的音频。',answers:['准确列40英语访客、多听展品这一观察、路线同时缩短使独立因果不确定、其他语言和无障碍路线尚未评估。','英文建议范围限定已有英语与路线条件，区分已观察和将来评估，提出对照路线或不同语言/无障碍场景验证，不把计划当完成或广泛适用证明。'],grading:'semantic',executionRequired:false}
    ],review:choice('tech-review','A team tested a parcel scanner on square boxes from one supplier. It detected most damaged labels. Irregular parcels were excluded and will be studied next month.','Which statement best preserves the evidence?',['All parcel shapes are covered','Evidence concerns the tested square boxes; irregular parcels remain untested','The supplier proved damaged labels never occur','Next month’s study has already succeeded'],'B','样本限定与计划状态必须保留。',['en-reading','en-structure','en-writing'])});

  const sdDiagnosticMaterial='某书店准备上线订单服务。读者下单可包含多种书，每本书有库存；一个订单必须记录各明细数量和下单时单价。支付成功后才进入待发货状态。客户端可能因超时重发相同支付通知，库存扣减、支付记录及订单状态不能产生重复结果。仓库处理发货任务时要求同一优先级按进入队列的先后取出。现有需求还规定：管理员可查询某日已支付订单总额；用户不能查看其他人的订单。';
  const sdDiagnostic=[
    diagnostic('sd-diag-schema',sdDiagnosticMaterial,'为了保留“同一订单多种书及每种书的数量/成交单价”，哪种关系设计最合适？',['把订单中所有书名拼进一个字符串列','订单表与图书表之间增加订单明细表，明细保存数量和成交单价','只保存图书当前价格，查询时作为历史成交价','每个用户只允许一张订单表'],'B','明细连接订单与图书并保存本次购买数量/成交单价；历史成交价不是当前商品价格。','sd-db',['sd-case','sd-design'],'从案例业务规则提取实体关系与历史事实',{A:'以字符串拼接替代明细关系，可能忽略多对多及逐项约束',C:'混淆商品当前属性与订单历史事实',D:'把业务实体与按用户分表混为一谈'}),
    diagnostic('sd-diag-payment',sdDiagnosticMaterial,'对于相同支付通知的重复到达，哪项更符合需求？',['每次到达都扣减库存以确保通知被处理','先返回成功，再异步随意修改库存','以稳定业务标识去重，并把相关状态变更放在满足一致性规则的事务中','仅把界面按钮变灰即可避免所有重复'],'C','需要服务端基于相同业务通知识别重复，同时协调扣库存/支付记录/状态；仅界面限制不能阻止网络重发。','sd-db',['sd-os','sd-engineering'],'连接重复请求、共享状态与事务性一致性',{A:'把到达次数当作独立业务次数',B:'遗漏相关状态的整体一致性约束',D:'把客户端交互限制当作服务端幂等保证'}),
    diagnostic('sd-diag-dispatch',sdDiagnosticMaterial,'同一优先级任务必须按到达顺序取出，哪种规则满足要求？',['后进先出的栈','先进先出的队列','按图书名称排序而忽略到达时间','每次随机抽一个任务'],'B','同优先级先到先处理是先进先出；优先级与到达次序可组合，但当前问题明确限定同一优先级。','sd-data',['sd-os','sd-case'],'从业务约束选择调度数据结构而非记术语',{A:'把最近到达优先与先到先处理颠倒',C:'用未授权排序规则替代需求',D:'忽略确定的公平/顺序约束'}),
    diagnostic('sd-diag-acceptance',sdDiagnosticMaterial,'哪组用例最直接覆盖订单隐私和重复支付的风险？',['只观察首页颜色和按钮位置','只看代码是否使用了类','只测一个管理员成功查询','甲尝试查乙订单被拒；同通知重复两次仍只扣一次库存并保留一致订单状态'],'D','两项可观察用例分别对应访问范围与重复处理要求；应核查业务状态而不仅看HTTP成功或界面。','sd-engineering',['sd-design','sd-case'],'把需求风险转成可观察的独立验收',{A:'把外观当作业务风险覆盖',B:'把实现形式当作功能正确证明',C:'用单个正常路径替代权限和重复风险覆盖'})
  ];

  const orderScenario='图书店准备记录订单：Order(order_id,user_id,status,paid_at)；Book(book_id,title,current_price,stock)；OrderItem(order_id,book_id,quantity,unit_price)。订单可以有多种书；同一订单同一本书只出现一行。quantity必须大于0；unit_price表示本次成交价；stock表示当前库存。每条明细必须引用已有订单与图书。支付通知携带payment_event_id与order_id，同一通知可能重发。业务要求支付记录、订单状态与库存变化协调完成，不能重复扣库存。';
  const sdOrder=pack({key:'sd-order-database',subject:'sd',title:'书店订单案例：建模、事务与风险验收',theme:'订单生命周期与数据库一致性',examTaskType:'软考软件设计师风格数据库与综合案例任务',practicalOutput:'把订单业务转成可解释的关系约束与事务边界，并设计能发现重复通知和历史价格错误的用例。',modules:['sd-db','sd-design','sd-case','sd-engineering'],scenario:orderScenario,
    teaching:'从业务事实抽实体，而不是先背范式名称：订单记录一次交易，明细记录交易与书的关系，单价属于本次交易事实。按(order_id,book_id)唯一及外键约束防止重复明细和悬空引用。支付处理要区分网络请求和业务事件，相同稳定标识的事件重试应返回已处理结果；事务把相关数据库状态变化协调提交或回滚，唯一约束/锁或适当隔离用于并发竞争。事务本身不会自动发明幂等标识。验收同时观察订单状态、支付记录和库存，不用“接口成功”替代业务一致性。这里仅评价题干规则，不替代生产支付系统设计。',activities:[activity('order-model','scenario','将业务转换成关系图','写出三种实体及连接关系；分别标出数量、成交单价与当前价格属于哪里，找出两个数据库约束。',orderScenario,['sd-db','sd-design','sd-case']),activity('order-fault','debugging','定位两种一致性错误','审核伪实现，指出历史价格和重复通知各会损坏什么；描述修复所需标识、约束及事务边界。','伪实现：展示旧订单时读取Book.current_price；收到支付通知就减库存并设status=paid，不记录payment_event_id；扣库存成功但设置状态失败时不回滚。',['sd-db','sd-case','sd-engineering']),activity('order-verify','comparison','比较验收日志是否充分','日志A仅有“200 OK”；日志B记录同通知重发前后库存、支付事件数量、订单状态及旧单价。列出B能支持什么、仍需增加什么并发/失败用例。','场景：原库存10，下单2本，支付通知发送两次。期望业务结果只扣2，事件仅处理一次；若中途失败应按事务边界保持一致，不编造真实运行日志。',['sd-db','sd-engineering','sd-design'])],
    diagnosis:choice('order-entry',orderScenario,'历史订单的成交单价应从哪里读取？',['当前Book.current_price','该订单的OrderItem.unit_price','今天店铺平均价格','再次询问支付平台当前价格'],'B','成交单价是明细上的历史事实，不随书当前价格修改。',['sd-db','sd-design','sd-case']),practice:choice('order-practice',orderScenario,'事务和幂等在本任务中的关系，哪项准确？',['有事务就不必记录重复业务标识','只要按钮禁用，网络就不会重发','幂等识别重复业务事件，事务协调相关数据库变更；两者不能互相替代','事务只改变界面状态'],'C','区分重复请求的识别与数据库变更整体一致性。',['sd-db','sd-case','sd-engineering']),criteria:['从新业务案例识别关系、历史事实和约束','根据重复/失败风险选择一致性处理与可观察验证'],criterionModuleIds:[['sd-db','sd-design','sd-case'],['sd-db','sd-engineering','sd-case']],
    tests:[[
      choice('order-test-a1','租赁平台中一次租单可租多台设备，每台设备记录本次租用天数和成交日租价。设备现行报价可随时调整。','哪种设计能保存每次租用事实？',['租单与设备之间设置租单明细，保存天数和本次日租价','查询历史租单时一律读现行报价','把所有设备ID拼成一个没有明细的字符串','所有用户共用一条租单记录'],'A','租单明细承载关联及历史价格/时长，不依赖当前报价。',['sd-db','sd-design','sd-case']),
      choice('order-test-a2','积分服务可能重复收到同一event_id的订单完成事件；积分余额与积分流水必须一致。','哪组处理与用例最符合规则？',['每次都加分并只测首页','只要流水写入成功便忽略余额失败','用稳定事件标识去重，余额与流水按事务规则一起变更，测试重放及中途失败','去掉流水表后宣称不存在重复问题'],'C','稳定事件标识+事务一致性+重放/故障的可观察验收分别覆盖风险。',['sd-db','sd-engineering','sd-case'])
    ],[
      choice('order-test-b1','报名系统中一个课程有多名学员，一名学员可报多门课；每次报名记录报名日期和当时应付金额。','哪项设计更符合业务？',['直接把日期放到学员表，所有课程共用','增加报名关系表，关联学员和课程并保存日期与本次金额','只保留课程当前价格来还原所有历史报名','把学员姓名作为唯一交易事实'],'B','报名是多对多关联且附有本次事件事实，应由关系表承载。',['sd-db','sd-design','sd-case']),
      choice('order-test-b2','票务系统扣减余票后创建购票记录。若创建失败只保留扣减；客户端超时重试可能再扣。','应优先补哪组验收？',['只检查字体颜色','只检查一次正常返回','只比较源代码行数','失败时状态按事务规则保持一致，重复业务请求不重复扣票，并核对余票与记录'],'D','失败和重试都会破坏一致性，必须观察两类业务状态。',['sd-db','sd-engineering','sd-case'])
    ]],hwCriteria:['给出新案例关系模型、历史事实与至少两项有效约束','提交一致性/重复处理说明及能观测结果的失败和重试用例'],homeworkCriterionModuleIds:[['sd-db','sd-design','sd-case'],['sd-db','sd-engineering','sd-case']],homework:[
      {prompt:'迁移任务：培训机构收费。学员可报多个班，报名保存当次费用与报名日期；一个收费回执payment_id可能重复到达。报名缴费状态、收费流水必须一致。\n提交① 表/字段/主键外键及唯一性或金额约束，解释为什么不能用班级现价还原已缴费用；② 收费事务与重复处理伪流程；③ 至少三条用例（正常、重复、写流水失败），逐项写输入及应检查的报名状态/流水数量。不要求声称真实执行过。',answers:['模型有学员、班级、报名关联并在报名保存当次费用/日期；列出明确主外键、关联唯一或费用约束；解释历史事实不能被现价覆盖。','稳定payment_id识别重复并防并发重复，报名状态与流水协调事务提交/回滚；正常/重复/失败用例均有具体输入和可观察预期，重复不新增业务流水，失败不留下矛盾状态。'],grading:'semantic',executionRequired:false},
      {prompt:'替代迁移：设备维修计费。工单可含多种零件，明细保存数量和当时单价；确认收费事件charge_event可能重发；工单已结算状态与收费记录需一致。\n提交① 工单、零件、明细关系及约束/历史价格说明；② 事务与幂等流程；③ 正常、重发、更新工单失败三类用例的输入与记录/状态预期。不用文本冒充实际系统执行。',answers:['工单与零件由明细联系，数量与当次价格保存在明细；主外键和唯一性/数量约束明确，当前零件报价变化不改历史明细。','以稳定charge_event去重并保护并发重复；收费记录和结算状态协调变更；三类可观察用例检查记录数量与工单状态，重发不重复收费，中途失败按边界保持一致。'],grading:'semantic',executionRequired:false}
    ],review:choice('order-review','订阅续费成功事件renewal_id可能重发。续费日期与支付记录必须对应，同一事件只能延长一次。','哪项方案同时覆盖题干风险？',['每次重发都延长，因为支付记录可晚点补','只禁用前端续费按钮','稳定事件标识去重，日期与支付记录协调变更，并核对重放前后日期和记录数量','只记录一条界面弹窗'],'C','区分幂等身份、一致性边界及实际业务状态验证。',['sd-db','sd-engineering','sd-case'])});

  const scheduleScenario='打印中心收到同优先级任务J1、J2、J3，必须按到达顺序取走；多个工作线程共同操作任务队列与completed计数。队列容量有限，空队列时工作线程应等待，满队列时提交方应等待。完成一次任务后计数加1。另有设备A和B，两类维护任务可能先持有不同设备再请求对方，存在相互等待风险。用户要求取任务顺序符合队列规则，最终计数等于实际完成任务数。';
  const sdSchedule=pack({key:'sd-task-scheduling',subject:'sd',title:'打印中心调度：队列、同步与可追踪执行',theme:'有限资源上的任务调度',examTaskType:'软考软件设计师风格的数据结构、操作系统与程序行为案例',practicalOutput:'从调度需求选结构，手工追踪并发读改写与资源等待，提出可验证的同步方案，而非只记“栈/锁”的定义。',modules:['sd-data','sd-os','sd-language','sd-case'],scenario:scheduleScenario,
    teaching:'业务先到先取对应FIFO，单个消费者选择队列即可，但多个线程共享队列还必须协调取出操作。completed++通常由读、加、写组成；不同线程交错读旧值会丢失更新，结构选对并不自动保证并发安全。限定按值传入整数形参时，函数内改形参不更新调用者变量；共享对象与语言规则需另行明确。空/满等待不应持有阻止对方推进的互斥锁持续忙等。资源A/B相反获取顺序可能形成循环等待，可统一获取顺序或采用其他满足约束的方案。验收用具体交错和资源图，不能以一次顺序运行证明所有并发安全。',activities:[activity('schedule-trace','scenario','画一张取任务时间线','依次提交J1、J2、J3，再取两次；写出队列中剩余任务。随后说明两个工作线程同时取队首时什么操作必须协调。',scheduleScenario,['sd-data','sd-os','sd-case']),activity('schedule-interleave','experiment','纸上复现丢失计数','按给出的确定交错追踪completed，而不是声称实际跑过；解释哪一步共享操作需要成为原子效果。','初值0：T1读0；T2读0；T1写1；T2写1。两次任务已经完成。再看伪函数increment(n)：n=n+1；调用方式限定按值传入整数，外部count初值0。比较两种计数错误的原因。',['sd-os','sd-language','sd-case']),activity('schedule-deadlock','debugging','审核维护流程','给两线程资源等待画箭头，指出闭环，并提供不会产生这一获取顺序冲突的改法；写一个应观察的失败/等待指标。','T1：持有A→请求B；T2：持有B→请求A。另一个缺陷：消费者握着队列互斥锁等待非空，而生产者必须拿同一锁才能入队。',['sd-data','sd-os','sd-language','sd-case'])],
    diagnosis:choice('schedule-entry',scheduleScenario,'仅考虑同优先级的到达先后规则，应先选择什么结构？',['后进先出的栈','先进先出的队列','不记录到达次序的集合','按任务名字倒序数组'],'B','FIFO满足先到先取，但并发共享操作仍需协调。',['sd-data','sd-case']),practice:choice('schedule-practice','count=7。T1读7；T2读7；T1写8；T2写8。两个任务都已完成。','这段交错最直接暴露什么问题？',['应该使用后进先出','变量名称太短','共享读改写丢失一次更新，需要同步或等效原子操作','整数按值传递一定修改所有调用者'],'C','期望9但得到8，问题是共享读改写交错，不能由命名或队列次序解决。',['sd-os','sd-language','sd-case']),criteria:['把调度约束转换成结构选择与具体状态追踪','区分共享读改写、参数传递和资源等待问题并选择对应处理'],criterionModuleIds:[['sd-data','sd-case'],['sd-os','sd-language','sd-case']],
    tests:[[
      choice('schedule-test-a1','客服工单同等级按进入顺序处理。依次入队K1、K2、K3，取走两项，再入队K4。','接下来应该依次取哪两项？',['K4、K3','K1、K2','K2、K4','K3、K4'],'D','FIFO追踪后K3先于新来的K4。',['sd-data','sd-case']),
      choice('schedule-test-a2','维修线程U先持有扫描器S再等待打印机P；线程V先持有P再等待S。同时另一个函数按值接收整数n，只在函数内修改n。','哪项解释最准确？',['相反资源获取顺序可能形成循环等待；函数内按值改整数不自动改调用者变量','按值形参修改能解除两个设备的等待','设备循环等待只需改变量名','只要使用队列就不需资源协调'],'A','两个独立机制分别是资源等待与整数值副本，不能互相替代。',['sd-os','sd-language','sd-case'])
    ],[
      choice('schedule-test-b1','批处理任务按进入顺序取出。提交M、N后取出M，再提交P、Q。','此时队首到队尾是什么？',['Q、P、N','N、P、Q','M、P、Q','P、N、Q'],'B','取走M后N保留，P和Q依次到尾。',['sd-data','sd-case']),
      choice('schedule-test-b2','共享sum初值4。W1读4；W2读4；W2写5；W1写5。另有按值函数f(x)把自己的整数x设为99，调用者变量仍是4。','哪项修复判断合适？',['两处都改用栈即可','两处都说明编译器一定错误','共享计数需协调读改写；想改变调用者需返回并赋值或使用明确支持的共享机制','按值整数形参必然是共享计数器'],'C','并发丢失更新和按值局部修改原因不同，需对应修复。',['sd-os','sd-language','sd-case'])
    ]],hwCriteria:['用新案例输入追踪FIFO及具体共享变量/调用行为','提出能消除给定等待或竞争问题的处理，并给出可观察验证'],homeworkCriterionModuleIds:[['sd-data','sd-language','sd-case'],['sd-os','sd-case']],homework:[
      {prompt:'迁移任务：图片转换服务有两个工作线程。任务同等级先到先取；初始队列[A,B]，取一次后加入C。共享done初值10，两个线程都先读10后分别写11。伪函数addOne(x)限定按值接收整数，仅在函数内x=x+1。设备锁规则：T1拿L再请求R，T2拿R再请求L。\n提交① 剩余队列及期望/交错后的done、外部整数调用addOne后的变化解释；② 队列取出和done同步方案、设备获取规则改法，以及至少三条可观察用例。纸上推演要标为推演，不冒充真实日志。',answers:['队列剩余B,C；两任务完成期望12而交错写得11；按值addOne仅改局部整数，外部不变；对应结构与程序语义说明清楚。','协调队列共享取出及done读改写或等效原子操作，统一设备获取顺序等有效方案；用例检查FIFO、多任务计数、相反竞争/等待并给具体输入与期望，无一次顺序执行证明全安全的夸大。'],grading:'semantic',executionRequired:false},
      {prompt:'替代迁移：视频缩略图服务依次提交[X,Y,Z]，取走X后加入W；sharedCount初值2，两个线程都读2并各写3。按值函数reset(n)仅将局部整数设0。消费者持有queueLock时持续等待队列变非空；生产者需要同一锁才能入队。\n提交① 队列、正确计数与交错计数、reset的外部效果；② 能让生产/消费推进且避免丢计数的设计；③ 正常、空队列、多线程计数三类用例的观测标准。',answers:['剩余Y,Z,W；两次完成期望4而交错结果3；按值reset不改变外部整数。说明FIFO和局部/共享行为有不同机制。','不在持锁阻止生产者的状态下持续忙等，使用能正确释放/等待/唤醒的协调或等效方案；共享读改写同步；三类用例明确输入/输出次序、等待可推进与最终计数，无死循环方案。'],grading:'semantic',executionRequired:false}
    ],review:choice('schedule-review','数据导入队列先提交R1、R2，取R1后加入R3。两个线程对共享完成数做未协调的读改写。','哪项结论与需求一致？',['下一项应是R3且读改写总安全','下一项应是R2，但FIFO本身不能保证共享计数的并发正确','用栈才能先取R2','变量是整数，所以所有读改写自动整体原子'],'B','结构顺序与共享同步须分别处理。',['sd-data','sd-os','sd-case'])});

  const apiScenario='社区借书应用需要查询自己的借阅记录并续借。用户登录后携带身份信息；服务端仍必须确认请求记录属于该用户，管理员有独立授权入口。续借请求可能因网络超时重发，需求规定相同request_id只延长一次。客户端与服务器使用TCP长连接；应用协议是“4字节长度+JSON正文”，一次接收可能拿到半条消息或多条消息。业务层负责借阅规则，传输层只负责解析消息，不能把网络接收回调与业务授权混成一处。';
  const sdApi=pack({key:'sd-api-design',subject:'sd',title:'借书服务案例：协议、职责与验收边界',theme:'从用户需求到可靠接口',examTaskType:'软考软件设计师风格需求、设计与网络综合案例',practicalOutput:'将借书服务约束变成清晰职责和协议处理，设计覆盖越权、消息分片与重复续借的验收用例。',modules:['sd-network','sd-design','sd-engineering','sd-case'],scenario:apiScenario,
    teaching:'沿一次业务请求画路径：字节到达→按长度解析消息→识别身份与授权→执行借阅规则→提交结果。TCP提供字节流，不保留应用消息边界，所以接收缓冲必须保留未完整部分并可能一次解析多条。登录只说明身份，不等于有权查看每条记录。清晰接口使传输、授权、业务规则有可描述职责；续借重试的request_id要代表稳定业务操作。验收从规则反推正常、越权、分片/合并、重复和失败情景，观察完整消息数量和借阅日期变化，不能仅观察按钮点击成功。',activities:[activity('api-path','scenario','画出一次续借的职责路径','把协议解析、身份/记录授权、续借规则、重复处理放到四个职责盒子；列出输入和输出，标出业务规则不能由哪一个盒子保证。',apiScenario,['sd-network','sd-design','sd-case']),activity('api-stream','experiment','纸上拆分两条消息','假设消息正文长度分别5和3，长度前缀各4字节。第一批接收含第一条前缀及2个正文字节；第二批含余3字节和第二条整条。列出何时得到完整消息、应保留什么。','这是确定的纸上缓冲模拟，不是实际网络运行。不要直接把每次recv结果当完整JSON。',['sd-network','sd-engineering','sd-case']),activity('api-review','debugging','审核错误接口与用例','找出伪实现中的越权、拆包和职责问题；为每个问题给具体输入与可观测预期。','伪实现：recv一次就JSON.parse；只检查token存在就读取任意record_id；重复续借每次都加7天；传输回调直接修改所有业务对象。现有用例只有“本人一次续借成功”。',['sd-network','sd-design','sd-engineering','sd-case'])],
    diagnosis:choice('api-entry',apiScenario,'一次TCP接收调用返回一段数据，应怎样理解？',['必然恰好一个JSON对象','必然包含所有剩余消息','可能是半条或多条消息，需按应用长度协议解析','有登录信息就无需解析协议'],'C','TCP是字节流，需要应用协议定义边界及缓冲。',['sd-network','sd-design']),practice:choice('api-practice',apiScenario,'登录用户甲请求用户乙的借阅record_id，最应在哪里检查什么？',['只由页面隐藏按钮即可','服务端业务访问入口检查身份对该记录的授权','只验证JSON能解析即可','只在客户端比较用户名'],'B','身份与记录授权不同，服务端必须按业务范围检查。',['sd-design','sd-engineering','sd-case']),criteria:['将协议与业务约束分到清晰职责，正确识别字节流处理','用需求派生可观察的越权、重复与消息边界验收'],criterionModuleIds:[['sd-network','sd-design','sd-case'],['sd-engineering','sd-design','sd-case']],
    tests:[[
      choice('api-test-a1','仓储终端采用“长度前缀+正文”发送盘点消息。recv第一次拿到前缀和半个正文，第二次拿到余下正文与下一条完整消息。','哪种处理符合协议？',['两次recv各当作一条消息直接执行业务','保留缓冲，正文完整才解析，并循环解析剩余完整消息','忽略长度前缀只看TCP包编号','第一批不完整就把整个连接当成功业务'],'B','应用层缓冲与长度协议保证完整消息，不由recv边界决定。',['sd-network','sd-design','sd-case']),
      choice('api-test-a2','员工报销接口需员工只能查看自己的报销单，同一submit_id重试不重复创建。','哪组验收最有针对性？',['甲读取乙报销单被拒；同submit_id重发后仅一条报销记录','只检查页面布局','只测管理员正常登录','查看是否用了某个流行框架'],'A','用业务输入和数据库/权限观测覆盖两条具体规则。',['sd-engineering','sd-design','sd-case'])
    ],[
      choice('api-test-b1','一个设备上报协议用换行分隔JSON消息，服务要求每条消息由独立业务处理器校验。','哪项设计合理？',['网络回调每次都一定以换行结束','将全部状态与权限校验放进界面按钮','传输解析器按协议缓冲和分帧，再调用有清晰输入约束的业务处理器','依赖TCP自动给出一个业务对象'],'C','明确字节流的应用边界与解析/业务职责，不能依赖TCP隐含消息。',['sd-network','sd-design','sd-case']),
      choice('api-test-b2','校园设备预约接口规定只有预约人能取消，cancel_id重发只取消一次；还需支持两条消息同批到达。','哪组用例覆盖这三个要求？',['本人正常点一次取消','只测连接建立','只测JSON格式错误','他人取消被拒、同cancel_id重放状态不二次变更、两条粘在一次接收中仍分别正确解析'],'D','三类可观察用例分别覆盖授权、幂等和应用消息解析。',['sd-network','sd-engineering','sd-design','sd-case'])
    ]],hwCriteria:['给出新接口的协议缓冲流程与业务职责/授权边界','提供覆盖消息分片合并、越权与重复业务的可观察用例'],homeworkCriterionModuleIds:[['sd-network','sd-design','sd-case'],['sd-network','sd-engineering','sd-case']],homework:[
      {prompt:'迁移任务：医院预约取消服务（只讨论题干软件规则）。普通用户只能取消自己的预约；同cancel_id只能将预约从active变为cancelled一次。传输协议是“长度前缀+JSON”，存在一条分两批到达和两条一批到达。\n提交① 字节解析/授权/业务处理三块职责及伪流程，说明缓冲未完整数据；② 四条用例：分片、合并、他人预约、重复取消，每条写输入/批次与应观察的消息数量、授权结果或状态。',answers:['清晰区分字节缓冲按前缀判断完整、授权检查身份对预约归属、业务取消与稳定cancel_id重复识别；未完整部分保留且完整消息可循环处理。','四条用例均具体：分片完成后只处理1消息、合并分别处理2消息、他人预约拒且不改状态、同cancel_id重放不重复业务状态变化；观测业务结果，不仅连接或页面。'],grading:'semantic',executionRequired:false},
      {prompt:'替代迁移：仓库领料接口。员工只能领自己获批申请的材料，issue_id重发只记一次领料。正文JSON以换行结尾；正文可能分两批，或两行同批收到。\n提交① 解析、归属/批准校验和领料处理的职责图与流程；② 分片、两行合并、未批准/他人申请、同issue_id重复四类用例，明确库存/领料记录/消息数量预期。',answers:['按给定换行协议缓冲并分帧，未完整行保留；服务端核验归属与批准，再调用稳定issue_id业务处理；职责不依赖客户端隐藏按钮。','用例描述真实输入批次和预期：分片不提前处理且最终1条、合并2条、越权/未批拒绝且库存不变、重复仅一次领料记录与扣减；不以200响应替代全部状态观察。'],grading:'semantic',executionRequired:false}
    ],review:choice('api-review','智能柜开锁接口使用长度前缀，授权只允许当前寄件人开自己的柜；相同open_id应代表同一业务动作。','哪项组合最合理？',['每次接收都直接开任意柜','客户端有登录按钮就足够','把协议解析与授权都交给TCP','按协议提取完整消息，服务端核验柜归属，稳定open_id识别重试并验收业务结果'],'D','消息、授权、重复是相互关联但不同的责任。',['sd-network','sd-design','sd-engineering','sd-case'])});

  const gameDiagnosticMaterial='项目中的无人机从(0,0)前往(3,4)，移动速度2单位/秒。当前实现每帧直接加0.2单位而不乘deltaTime，因此帧率变化时速度变化。项目还把目标位置通过网络每200ms发送一次，收到新位置就瞬移；测试发现延迟下画面抖动，但只做过本机零延迟观察。性能日志给出同一场景CPU帧耗时22ms、GPU帧耗时7ms，暂未进一步细分CPU阶段。';
  const gameDiagnostic=[
    diagnostic('game-diag-direction',gameDiagnosticMaterial,'从(0,0)前往(3,4)，用于按固定速度移动的单位方向是哪项？',['(3,4)','(0.6,0.8)','(1,1)','(4,3)'],'B','位移长度5，归一化方向为(3/5,4/5)；再乘速度和时间获得步长。','game-math',['game-engine'],'把目标位移转成单位方向并联系按时间移动',{A:'把位移长度直接混入方向，可能重复放大速度',C:'以相同分量替代实际方向',D:'交换坐标且未归一化'}),
    diagnostic('game-diag-time',gameDiagnosticMaterial,'要保持不同帧率下的近似相同速度，应怎样改变按帧移动规则？',['每帧固定移动更大距离','只改变量名','每步移动量由速度×deltaTime决定并检查越过目标','只降低贴图分辨率'],'C','步长与经过时间关联，结合单位方向；接近目标还需防过冲。','game-engine',['game-math','game-performance'],'将时间步与行为验证连接',{A:'增加常量仍保留帧率依赖',B:'没有改变运动计算机制',D:'把渲染成本手段当作移动语义修复'}),
    diagnostic('game-diag-profile',gameDiagnosticMaterial,'根据已有日志，优化前最有依据的下一步是什么？',['先细分测量CPU阶段，并保持对比场景一致','立即删光所有GPU特效','认定网络是唯一原因','认定CPU每个函数都一样慢'],'A','已有样本CPU帧耗时较高，先细分CPU阶段；这不是所有场景瓶颈的证明，也不能直接决定某个函数。','game-performance',['game-engine'],'用实际范围内测量选择下一步而非凭印象',{B:'GPU样本不是当前较高耗时，删除特效无足够依据',C:'材料没有网络独立耗时因果证据',D:'没有阶段测量却推广到每个函数'}),
    diagnostic('game-diag-network',gameDiagnosticMaterial,'对于抖动问题，哪组扩展测试最有用？',['只重复本机零延迟截图','只检查角色名字长度','只记录一帧最好成绩','在可控延迟/抖动/丢包下记录接收时序、位置误差与修正行为'],'D','真实网络条件与时间线支持同步验证；需观测权威状态与客户端行为而非只有视觉印象。','game-network',['game-engine','game-performance'],'从零延迟样本扩展到网络条件与可观测证据',{A:'测试条件仍未覆盖已知风险',B:'名字长度与给定同步机制无依据关联',C:'最佳单帧不能代表网络时序表现'})
  ];

  const moveScenario='设计一个二维无人机移动原型：当前(0,0)，目标(3,4)，速度2单位/秒。每次tick收到deltaTime；方向需要归一化，移动距离不能超过剩余距离，到达后停下。比较同样0.5秒的一次tick与5次0.1秒tick，位置应近似相同；调用次数不同但不能据此直接声称真实引擎帧率改善。';
  const gameMove=pack({key:'game-drone-movement',subject:'game',title:'无人机抵达目标：向量、时间步与实际验证',theme:'可复现的目标移动原型',examTaskType:'实用项目任务 · 用实际输出验收运动行为',practicalOutput:'实现按秒移动且不会越过目标的二维原型，运行不同时间步输入并用实际位置与调用次数解释结果。',modules:['game-math','game-engine','game-performance'],minutes:40,hwMinutes:15,scenario:moveScenario,
    teaching:'目标减当前位置给出位移，长度代表剩余距离，非零时方向=位移/长度。单步距离=min(speed×deltaTime,剩余距离)，再沿单位方向移动；剩余距离接近0时直接保持目标，避免除0。deltaTime是经过时间而不是帧编号；比较相同总时长下不同分步能发现按帧常量错误。调用次数是本原型的工作量指标，不等于CPU毫秒或真实帧率；需要真实耗时结论时应在同样场景单独测量。纸上计算和实际执行输出分别标记。',activities:[activity('move-vector','scenario','给无人机算第一步','先算(3,4)位移的长度和方向，再算dt=0.5秒的一步，说明为什么不能直接把(3,4)乘速度。',moveScenario,['game-math','game-engine']),activity('move-bug','debugging','审查错误运动器','指出固定按帧步长、未归一化和零距离风险，说明每一处应怎样修复。','伪代码：dx=target.x-x; dy=target.y-y; x+=dx*0.2; y+=dy*0.2; //忽略dt且步长依赖剩余距离\n第二种伪代码：x+=speed*dt*dx/length; y+=speed*dt*dy/length; //未处理length=0或大步长过冲',['game-math','game-engine']),activity('move-run','experiment','运行一份最小时间步记录','在应用实验区用JavaScript写可复现tick并运行两条时间步序列；记录实际位置、调用次数及零距离/过冲行为。不能把预计输出当真实运行日志。','输入集：起点(0,0)，目标(3,4)，速度2。序列一[0.5]，序列二[0.1,0.1,0.1,0.1,0.1]；可用JSON.stringify输出每步坐标和count。不同计数不构成真实性能提升结论。',['game-math','game-engine','game-performance'])],
    diagnosis:choice('move-entry',moveScenario,'速度2、dt=0.5，从(0,0)走第一步应到哪里？',['(3,4)','(1,1)','(0.6,0.8)','(1.2,1.6)'],'C','方向(0.6,0.8)，本步距离1，所以位置(0.6,0.8)。',['game-math','game-engine']),practice:choice('move-practice','剩余距离0.4，速度3，dt=0.5；算法要求到达后停止。','本步应走多远？',['1.5，越过目标才算快','0.4，使用剩余距离限制步长','0，任何dt都不能移动','3，与dt无关'],'B','speed×dt=1.5，但允许最大剩余距离0.4，故需限幅。',['game-math','game-engine']),criteria:['在新输入中正确处理方向、时间步与到达限幅','用可比较的时间步/计数或测量证据辨别行为与性能结论'],criterionModuleIds:[['game-math','game-engine'],['game-engine','game-performance']],
    tests:[[
      choice('move-test-a1','起点(1,1)，目标(1,7)，速度3单位/秒，dt=1秒，按单位方向且限幅移动。','新位置是多少？',['(1,4)','(4,7)','(1,10)','(1,2)'],'A','位移(0,6)，方向(0,1)，步长3，得到(1,4)。',['game-math','game-engine']),
      choice('move-test-a2','两个同方向实现比较：A每帧移动固定0.1；B每帧移动speed×dt。测试分别用10步0.1秒和20步0.05秒，总时长均1秒。另只记录了调用次数。','哪项结论合理？',['A在两序列总位移一定相同','B无需处理到达目标','调用次数直接等于真实FPS','B应保持相同总时长下位移；调用次数可比较，但不能单独证明真实帧率提升'],'D','时间缩放与工作量计数不同于真实耗时/帧率证据。',['game-engine','game-performance'])
    ],[
      choice('move-test-b1','起点(-2,0)，目标(2,0)，速度5单位/秒，dt=2秒，到达后停止。','限幅算法应得到什么位置？',['(8,0)','(2,0)','(-2,10)','(0,0)'],'B','剩余4而候选步长10，限制到4恰好到目标。',['game-math','game-engine']),
      choice('move-test-b2','同一移动原型在相同起点/目标/总时长下，分步序列产生相同位置，但一份日志未记录设备、场景或CPU/GPU耗时。','哪项说明恰当？',['已经证明所有引擎场景FPS提升','已经证明网络同步正确','支持这些输入下时间步行为一致；真实耗时或引擎性能还需要可比测量','证明所有deltaTime输入永不出错'],'C','当前证据只覆盖所测行为，不能跨范围推性能、网络或全部输入。',['game-engine','game-performance'])
    ]],hwCriteria:['提交可运行的归一化/时间步/限幅实现并正确处理新输入及零距离','提供实际执行输出，对比相同总时长的分步与调用次数，准确限定结论'],homeworkCriterionModuleIds:[['game-math','game-engine'],['game-engine','game-performance']],homework:[
      {prompt:'独立项目：用JavaScript实现tick(pos,target,speed,dt)二维移动；起点(0,0)、目标(6,8)、速度5。分别运行[1]和[0.2,0.2,0.2,0.2,0.2]；另运行dt=3的到达限幅以及起点等于目标的情况。\n提交① 完整可运行代码；② 在应用实验区真实运行的输出（含各序列最终位置和tick计数）；③ 对比解释哪些是运动证据、哪些还不是真实性能结论。浮点误差可用合理容差，不要求凭记忆写固定字符串。',answers:['代码由位移长度得单位方向，乘speed×dt且以剩余距离限幅，零距离安全；两1秒序列最终约(3,4)，dt3到(6,8)，已在目标保持不动，无NaN。','有对应代码实际执行输出与实验记录，count分别1与5，两序列位置相近；说明调用数与行为证据，未测真实耗时不能断言FPS改善；包含过冲/零距离结果。'],grading:'semantic',executionRequired:true},
      {prompt:'替代独立项目：同样实现tick，但起点(2,2)、目标(2,12)、速度4。比较[1.5]与[0.5,0.5,0.5]；运行dt=4检查不越过目标，并运行目标等于当前位置。\n提交完整JavaScript、在应用实验区真实执行的坐标/tick计数日志与简短结论。代码须可重复运行；不要用预计结果冒充真实输出。',answers:['实现归一化、speed×dt、剩余距离限幅与零距离保护；两1.5秒序列最终约(2,8)，dt4到(2,12)，零距离不移动无无效数值。','有匹配的实际执行记录，计数1与3且同总时长位置相同，过冲与零距离输出被覆盖；区分行为/调用次数证据和尚未测的引擎性能。'],grading:'semantic',executionRequired:true}
    ],review:choice('move-review','角色在(4,4)，目标也在(4,4)。tick使用位移除以长度来归一化。','最应先怎样处理？',['继续除以0，输出自然正确','增大速度掩盖问题','先检查接近零的剩余距离，保持目标位置并不进行除0','把目标随机改成其他位置'],'C','零距离是明确边界，需要安全停止，不改变任务目标。',['game-math','game-engine'])});

  const syncScenario='多人原型由服务器决定角色状态。客户端按seq序号接收位置样本；样本可能晚到、乱序或重复。基线算法收到样本立即瞬移。新原型先保留按序样本，在明确的显示时刻用两个样本线性插值；没有覆盖显示时刻的两样本时使用题干给定的保守保持策略，不假装已知道未来位置。每份实验记录输入包时序、接纳/忽略数量、显示位置及最大偏差；对照基线和原型必须用同一包序列。';
  const gameSync=pack({key:'game-network-replay',subject:'game',title:'同步回放原型：用乱序与延迟材料验证修正',theme:'可重放的网络样本时间线',examTaskType:'实用项目任务 · 状态权威、插值与对照实验',practicalOutput:'实现一个小型样本接纳/插值回放器，用相同延迟与乱序输入对照行为，并解释新技术原型的证据边界。',modules:['game-network','game-engine','game-performance','game-frontier'],minutes:45,hwMinutes:18,scenario:syncScenario,
    teaching:'先明确权威与显示：服务器样本描述权威历史状态，客户端显示位置由缓冲与插值策略得到，不是另一份权威。seq可用于识别重复或过旧包，时间戳确定插值的横坐标；不能把包到达顺序当状态生成顺序。本任务只用一维线性插值：alpha=(displayTime-t0)/(t1-t0)，x=x0+(x1-x0)×alpha，且只在两样本覆盖的区间使用。验证必须固定输入时间线，记录接纳、忽略与显示结果；简单模拟是验证算法的证据，不能声称已证明真实引擎网络性能或规模。采用缓冲插值前用最小回放原型验证边界，再考虑工程扩展。',activities:[activity('sync-timeline','scenario','画权威与到达两条时间线','分别按样本生成时间和到达时间排列事件，解释乱序时为什么不能让较老样本覆盖更新状态。',syncScenario+'\n包P：seq1,t=0,x=0，arrival=0.1；包Q：seq3,t=2,x=10，arrival=2.1；包R：seq2,t=1,x=5，arrival=2.2。',['game-network','game-engine']),activity('sync-compare','comparison','比较直接跳与缓冲显示','在有seq1(t0,x0)与seq2(t2,x8)时，计算displayTime=1的插值位置；说明它与“刚收到哪个包就显示哪个位置”的区别。','请明确这是纸上结果；保守策略用于无覆盖样本，不能自己外推未来权威位置。',['game-network','game-engine','game-frontier']),activity('sync-replay','experiment','建立可重放的小实验','写一个最小JavaScript回放器，记录每个seq是否接纳和给定时刻的显示位置。比较两策略时固定包序列和显示时刻；输出材料必须来自真实运行。','用数组给出{seq,t,x,arrival}，只对本任务一维数据处理。基线可忽略过旧包后显示最新值；新策略按规则保留样本并插值。日志含样本/接纳数，不把小模拟的计数当真实CPU/GPU性能。',['game-network','game-engine','game-performance','game-frontier'])],
    diagnosis:choice('sync-entry',syncScenario,'迟到的seq=4包在seq=5已接纳后到达，本任务保守接纳规则应怎样处理？',['无条件回退到seq4','识别为过旧，不覆盖更新权威样本','把它当seq6','删除全部缓冲样本'],'B','显式序号规则防止旧样本使状态倒退；实际系统策略必须明确，这里按题干规则评价。',['game-network','game-engine']),practice:choice('sync-practice','有两样本(t=0,x=2)与(t=4,x=10)，只在覆盖区间内线性插值。','显示时刻t=1的位置是多少？',['10','2','4','12'],'C','alpha=1/4，x=2+(10-2)/4=4。',['game-network','game-engine','game-frontier']),criteria:['按新时序案例区分权威、乱序接纳与显示插值','用固定条件对照和边界样本验证原型，明确可推广范围'],criterionModuleIds:[['game-network','game-engine'],['game-network','game-performance','game-frontier']],
    tests:[[
      choice('sync-test-a1','回放器已接纳seq12。随后到达seq11和重复seq12，本任务规则是只接纳更大的序号。','应产生什么结果？',['接纳两个并令状态回退','两个都不作为新样本接纳，不覆盖seq12','重复seq12视为seq13','序号和接纳规则无关'],'B','按题干只接纳严格增加序号，旧和重复都不形成新更新。',['game-network','game-engine']),
      choice('sync-test-a2','团队想比较新缓冲方案与直接显示方案。只跑了新方案的零延迟5包，并声称大规模互联网体验已经更好。','哪项补证最合适？',['用相同延迟/乱序包序列和显示时刻跑两方案，记录输出及边界；规模结论需另测','只改方案名称','只保留最好一帧截图','删除所有异常输入'],'A','对照条件与覆盖范围决定能支持的结论，新技术不能凭小单样本推广。',['game-network','game-performance','game-frontier'])
    ],[
      choice('sync-test-b1','已有样本(t=2,x=6)、(t=6,x=14)，显示时刻t=3在区间内使用线性插值。','显示位置是多少？',['14','6','8','20'],'C','alpha=(3-2)/(6-2)=1/4，x=6+8/4=8。',['game-network','game-engine']),
      choice('sync-test-b2','一个新同步原型只在10个一维样本上运行，日志显示重复包被忽略，插值输出符合这些输入。','哪种报告准确？',['所有真实网络条件均已验证','支持这些样本下的行为；需补丢包/覆盖不足和目标规模测试，不能推断真实引擎性能','以后不必进行对照','所有玩家都将没有抖动'],'B','小原型证明范围内算法行为，不保证未测网络、规模或真实性能。',['game-network','game-performance','game-frontier'])
    ]],hwCriteria:['提供可运行的序号接纳与覆盖区间插值实现，输出符合新输入','提交实际回放与固定条件对照记录，覆盖重复/乱序/无覆盖并限制结论'],homeworkCriterionModuleIds:[['game-network','game-engine'],['game-network','game-performance','game-frontier']],homework:[
      {prompt:'独立回放：按到达数组处理[ {seq:10,t:0,x:0}, {seq:12,t:2,x:12}, {seq:11,t:1,x:6}, {seq:12,t:2,x:12} ]。规则：只接纳严格大于已接纳最大seq的样本；保留已接纳样本供插值。显示时刻1若两样本覆盖则插值；时刻3无覆盖则保持最近已接纳样本值，不能外推。\n提交① 完整可运行JavaScript；② 实际执行的接纳/忽略记录及t1/t3显示位置；③ 在同一输入下与直接显示最新接纳样本的基线对照，解释模拟证明什么及真实网络/规模还缺什么。',answers:['可运行实现接纳seq10和12，忽略11及重复12；用t0,x0与t2,x12在t1插值得6；t3无覆盖按保持策略得12，权威与显示区分清楚。','真实实验输出包含接纳2/忽略2与显示结果，基线同输入/同显示时刻明确，比较不伪造实际网卡/引擎耗时；说明需要额外延迟丢包/规模及真实性能验证，小模拟不保证在线体验。'],grading:'semantic',executionRequired:true},
      {prompt:'替代独立回放：输入[ {seq:20,t:0,x:4}, {seq:21,t:4,x:20}, {seq:21,t:4,x:20}, {seq:19,t:-1,x:0} ]；只接纳严格递增序号，保留样本，t=1与t=2在覆盖区间插值，t=5无覆盖则保持最新已接纳样本。\n提交可运行JavaScript和实际接纳日志/三个显示时刻结果；与相同输入的直接显示基线比较，解释重复/乱序边界和原型范围，不把计数当真实性能。',answers:['接纳20/21，忽略重复21和旧19；插值t1=8,t2=12，t5按保持策略20；代码安全处理无覆盖且不外推未给定未来状态。','实际执行记录与代码一致，基线同包序列/显示时刻，有接纳忽略数量及边界输出；明确仅一维固定输入原型证据，未验证真实网络负载/引擎性能或所有情形。'],grading:'semantic',executionRequired:true}
    ],review:choice('sync-review','已接纳样本(t=0,x=5)和(t=2,x=9)。本任务明确只在覆盖区间插值，区间外保持最新已接纳值。','t=3时应显示什么且如何解释？',['11，因为可以无条件外推未来','9，这是给定无覆盖保持策略，不是已知未来权威位置','5，因为所有新包都无效','0，因为超出区间就删除对象'],'B','保持策略有明确范围，不能将保持显示解读为新未来权威样本。',['game-network','game-engine'])});

  return {
    en:{title:'雅思英语',target:'以雅思备考任务推进阅读理解与准确表达；目标分数由学习者设置',description:'从整段新材料起步，依据错题追查词句理解、关系和结论范围，再把知识带回另一份阅读任务。题型为自编练习，不等同完整官方考试。',subject:'英语',source,variants:[{id:'academic',title:'学术类 Academic',description:'偏校园、科技与研究材料；本地主题是技能小闭环，不是全套考试或分数预测。'},{id:'general',title:'培训类 General Training',description:'偏日常服务、公告与实用任务；可使用城市主题练习，AI按所选方向设计后续新材料。'}],diagnostic:{title:'大学通行证：完整材料任务诊断',material:enDiagnosticMaterial,source,questions:enDiagnostic},themes:[enCampus,enCity,enTech]},
    sd:{title:'软考 · 软件设计师',target:'以软件设计师备考的综合案例与可观察解题产出推进',description:'先阅读完整业务约束，再从答题证据扩散到数据库、设计、算法、操作系统或测试。仅训练材料列出的范围，不宣称已覆盖官方大纲或预测通过。',subject:'软件设计师',source,variants:[{id:'software-designer',title:'软件设计师',description:'当前内置目标为软件设计师案例练习；其他级别应另设目标与新任务，不自动混用。'}],diagnostic:{title:'书店订单：综合业务任务诊断',material:sdDiagnosticMaterial,source,questions:sdDiagnostic},themes:[sdOrder,sdSchedule,sdApi]},
    game:{title:'游戏开发 · 实用项目',target:'以能运行、能观察结果的项目原型推进',description:'从具体行为问题进入，连接数学、引擎、网络与测量。用真实实验输出验收，每轮小原型只支持已测范围。',subject:'游戏开发',source,variants:[{id:'prototype',title:'可运行原型',description:'使用小型JavaScript原型验证算法，工程迁移到实际引擎时需重新运行核对。'}],diagnostic:{title:'无人机原型：行为与测量任务诊断',material:gameDiagnosticMaterial,source,questions:gameDiagnostic},themes:[gameMove,gameSync]}
  };
})();
